import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { api, API_ORIGIN } from "../api";
import { useAuth } from "../auth/AuthContext";

type Section="dashboard"|"applications"|"faq"|"gallery"|"vacancies"|"content";
type FAQ={id:string;question_en:string;answer_en:string;question_am?:string;answer_am?:string;is_published:boolean;sort_order:number};
type Vacancy={id:string;title_en:string;location?:string;closing_date?:string;status:string};
type Album={id:string;title_en:string;photo_count:number;is_published:boolean;cover_image_url?:string};
type Application={id:string;reference:string;organization_name:string;transport_sector:string;submitted_at:string;status:string};

export default function Admin(){
 const [section,setSection]=useState<Section>("dashboard"),[toast,setToast]=useState(""),[stats,setStats]=useState<any>({total:0,pending:0,review:0,approved:0,rejected:0});
 const {user,logout}=useAuth(); const notify=(m:string)=>{setToast(m);setTimeout(()=>setToast(""),2200)};
 useEffect(()=>{api("/admin/application-stats").then(r=>setStats(r.stats)).catch(()=>{})},[]);
 return <div className="admin-shell"><aside className="admin-sidebar"><Link className="admin-brand" to="/"><span>ETEF</span><strong>ADMIN</strong></Link><div className="admin-sidebar-label">WORKSPACE</div><nav className="admin-nav">{([["dashboard","⌂","Dashboard"],["applications","◎","Applications"],["faq","?","FAQ"],["gallery","▧","Gallery"],["vacancies","▤","Vacancies"],["content","◈","Content"]] as [Section,string,string][]).map(([k,i,l])=><button key={k} className={section===k?"active":""} onClick={()=>setSection(k)}><span>{i}</span>{l}</button>)}</nav><div className="admin-sidebar-bottom"><span>SIGNED IN</span><strong>{user?.fullName}</strong><small>{user?.role}</small><button className="admin-signout" onClick={()=>logout()}>Sign out</button><Link to="/">View public site ↗</Link></div></aside><main className="admin-main"><header className="admin-topbar"><div><span className="eyebrow">ETEF DIGITAL PLATFORM</span><h1>{sectionTitle(section)}</h1></div><div className="admin-status"><i/> Secure session</div></header>{section==="dashboard"&&<Dashboard stats={stats} setSection={setSection}/>} {section==="applications"&&<Applications notify={notify}/>} {section==="faq"&&<FaqManager notify={notify}/>} {section==="gallery"&&<GalleryManager notify={notify}/>} {section==="vacancies"&&<VacancyManager notify={notify}/>} {section==="content"&&<ContentManager notify={notify}/>}</main>{toast&&<div className="admin-toast">✓ {toast}</div>}</div>
}
function sectionTitle(s:Section){return({dashboard:"Dashboard",applications:"Membership applications",faq:"FAQ manager",gallery:"Gallery manager",vacancies:"Job vacancies",content:"Website content"} as any)[s]}
function Dashboard({stats,setSection}:{stats:any;setSection:(s:Section)=>void}){return <div className="admin-content"><div className="admin-stat-grid"><div className="admin-stat"><strong>{stats.total}</strong><span>Membership applications</span><small>{stats.pending} pending</small></div><div className="admin-stat"><strong>{stats.review}</strong><span>Needs review</span><small>Applications in review</small></div><div className="admin-stat"><strong>{stats.approved}</strong><span>Approved</span><small>Membership decisions</small></div><div className="admin-stat"><strong>{stats.rejected}</strong><span>Rejected</span><small>Closed applications</small></div></div><div className="admin-two-col"><section className="admin-panel"><div className="panel-heading"><div><span className="eyebrow">QUICK ACTIONS</span><h2>Manage public information</h2></div></div><div className="quick-grid"><Quick title="Review applications" text="Check incoming membership registrations." onClick={()=>setSection("applications")}/><Quick title="Update FAQ" text="Add, edit or publish answers." onClick={()=>setSection("faq")}/><Quick title="Manage gallery" text="Create event albums and publish them." onClick={()=>setSection("gallery")}/><Quick title="Post vacancy" text="Publish current job opportunities." onClick={()=>setSection("vacancies")}/></div></section><section className="admin-panel"><div className="panel-heading"><div><span className="eyebrow">SECURITY</span><h2>Protected publishing workspace.</h2></div></div><p className="admin-copy">Changes are now sent to PostgreSQL through authenticated API requests. Publishing actions require a valid administrator session and CSRF token.</p><div className="admin-rule"><span>01</span><b>Sign in</b><span>→</span><b>Edit</b><span>→</span><b>Publish</b></div></section></div></div>}
function Quick({title,text,onClick}:{title:string;text:string;onClick:()=>void}){return <button className="quick-action" onClick={onClick}><strong>{title}</strong><span>{text}</span><b>→</b></button>}
function Applications({notify}:{notify:(m:string)=>void}){const[rows,setRows]=useState<Application[]>([]);const[filter,setFilter]=useState("ALL");const load=()=>api<{items:Application[]}>(`/admin/applications${filter==="ALL"?"":`?status=${filter}`}`).then(r=>setRows(r.items));useEffect(()=>{load().catch(()=>notify("Unable to load applications"))},[filter]);const update=async(id:string,status:string)=>{try{await api(`/admin/applications/${id}`,{method:"PATCH",body:JSON.stringify({status})});notify("Application status updated");load()}catch(e:any){notify(e.message)}};return <div className="admin-content"><div className="admin-toolbar"><p>Real membership applications from PostgreSQL.</p><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="ALL">All</option><option value="PENDING">Pending</option><option value="REVIEW">Review</option><option value="APPROVED">Approved</option><option value="REJECTED">Rejected</option></select></div><section className="admin-panel table-panel"><table><thead><tr><th>Reference</th><th>Organization</th><th>Sector</th><th>Submitted</th><th>Status</th><th>Action</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.reference}</td><td><strong>{r.organization_name}</strong></td><td>{r.transport_sector}</td><td>{new Date(r.submitted_at).toLocaleDateString()}</td><td><span className={`status-pill ${r.status==="REJECTED"?"closed":""}`}>{r.status}</span></td><td><select className="mini-select" value={r.status} onChange={e=>update(r.id,e.target.value)}><option value="PENDING">Pending</option><option value="REVIEW">Review</option><option value="APPROVED">Approve</option><option value="REJECTED">Reject</option></select></td></tr>)}</tbody></table>{!rows.length&&<div className="admin-empty">No applications found.</div>}</section></div>}
function FaqManager({notify}:{notify:(m:string)=>void}){const[items,setItems]=useState<FAQ[]>([]),[editing,setEditing]=useState<FAQ|null>(null),[q,setQ]=useState(""),[a,setA]=useState("");const load=()=>api<{items:FAQ[]}>("/admin/faqs").then(r=>setItems(r.items));useEffect(()=>{load().catch(()=>notify("Unable to load FAQs"))},[]);const save=async()=>{if(!q.trim()||!a.trim())return notify("Question and answer are required");try{await api(editing?`/admin/faqs/${editing.id}`:"/admin/faqs",{method:editing?"PATCH":"POST",body:JSON.stringify({questionEn:q,answerEn:a,isPublished:editing?.is_published||false})});setQ("");setA("");setEditing(null);notify("FAQ saved");load()}catch(e:any){notify(e.message)}};return <div className="admin-content"><div className="admin-two-col"><section className="admin-panel"><div className="panel-heading"><div><span className="eyebrow">{editing?"EDIT ENTRY":"NEW ENTRY"}</span><h2>{editing?"Edit FAQ":"Add FAQ"}</h2></div></div><label className="admin-field"><span>Question (English)</span><input value={q} onChange={e=>setQ(e.target.value)}/></label><label className="admin-field"><span>Answer (English)</span><textarea value={a} onChange={e=>setA(e.target.value)}/></label><div className="admin-actions"><button className="admin-button dark" onClick={save}>{editing?"Save changes":"Add FAQ"}</button>{editing&&<button className="admin-button light" onClick={()=>{setEditing(null);setQ("");setA("")}}>Cancel</button>}</div></section><section className="admin-panel"><div className="panel-heading"><div><span className="eyebrow">DATABASE CONTENT</span><h2>FAQ entries</h2></div></div>{items.map(x=><div className="content-row" key={x.id}><div><strong>{x.question_en}</strong><p>{x.answer_en}</p><small>{x.is_published?"Published":"Draft"}</small></div><div className="row-actions"><button onClick={()=>{setEditing(x);setQ(x.question_en);setA(x.answer_en)}}>Edit</button><button onClick={async()=>{try{await api(`/admin/faqs/${x.id}`,{method:"PATCH",body:JSON.stringify({isPublished:!x.is_published})});notify(x.is_published?"FAQ unpublished":"FAQ published");load()}catch(e:any){notify(e.message)}}}>{x.is_published?"Unpublish":"Publish"}</button></div></div>)}</section></div></div>}
function GalleryManager({notify}:{notify:(m:string)=>void}){
 const [items,setItems]=useState<Album[]>([]),[title,setTitle]=useState(""),[selected,setSelected]=useState<Album|null>(null),[photos,setPhotos]=useState<Photo[]>([]),[files,setFiles]=useState<File[]>([]),[loading,setLoading]=useState(false);
 const load=()=>api<{items:Album[]}>("/admin/gallery/albums").then(r=>setItems(r.items));
 useEffect(()=>{load().catch(()=>notify("Unable to load gallery"))},[]);
 const openAlbum=async(album:Album)=>{setSelected(album);setFiles([]);try{const r=await api<{items:Photo[]}>(`/admin/gallery/albums/${album.id}/items`);setPhotos(r.items)}catch(e:any){notify(e.message)}};
 const add=async()=>{if(!title.trim())return notify("Album title is required");try{await api("/admin/gallery/albums",{method:"POST",body:JSON.stringify({titleEn:title,isPublished:false})});setTitle("");notify("Album created");load()}catch(e:any){notify(e.message)}};
 const upload=async()=>{if(!selected||!files.length)return notify("Select one or more images");setLoading(true);try{const form=new FormData();files.forEach(file=>form.append("photos",file));const r=await api<{items:Photo[];skipped:number}>(`/admin/gallery/albums/${selected.id}/items`,{method:"POST",body:form});setFiles([]);notify(`${r.items.length} image${r.items.length===1?"":"s"} uploaded${r.skipped?` · ${r.skipped} skipped`:""}`);await openAlbum(selected);await load()}catch(e:any){notify(e.message)}finally{setLoading(false)}};
 const remove=async(photo:Photo)=>{if(!selected||!window.confirm("Delete this photo permanently?"))return;try{await api(`/admin/gallery/albums/${selected.id}/items/${photo.id}`,{method:"DELETE"});notify("Photo deleted");openAlbum(selected);load()}catch(e:any){notify(e.message)}};
 const cover=async(photo:Photo)=>{if(!selected)return;try{await api(`/admin/gallery/albums/${selected.id}/items/${photo.id}/cover`,{method:"POST",body:JSON.stringify({})});notify("Album cover updated");openAlbum(selected);load()}catch(e:any){notify(e.message)}};
 const toggle=async(album:Album)=>{try{await api(`/admin/gallery/albums/${album.id}`,{method:"PATCH",body:JSON.stringify({isPublished:!album.is_published})});notify(album.is_published?"Album unpublished":"Album published");load()}catch(e:any){notify(e.message)}};
 const deleteAlbum=async(album:Album)=>{if(!window.confirm(`Delete “${album.title_en}” and all its photos?`))return;try{await api(`/admin/gallery/albums/${album.id}`,{method:"DELETE"});notify("Album deleted");if(selected?.id===album.id){setSelected(null);setPhotos([])}load()}catch(e:any){notify(e.message)}};
 return <div className="admin-content">
  <section className="admin-panel">
   <div className="panel-heading"><div><span className="eyebrow">EVENT ALBUMS</span><h2>Gallery library</h2><p className="panel-subcopy">Upload optimized JPEG, PNG or WebP photographs. Maximum 10 files per upload, 5 MB each.</p></div><div className="inline-create"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="New album title"/><button className="admin-button dark" onClick={add}>Create album</button></div></div>
   <div className="album-admin-grid">{items.map(x=><article className={`album-admin-card ${selected?.id===x.id?"selected":""}`} key={x.id}>
    <button className="album-admin-art-button" onClick={()=>openAlbum(x)} aria-label={`Open ${x.title_en}`}><div className="album-admin-art">{x.cover_image_url?<img src={`${API_ORIGIN}${x.cover_image_url}`} alt=""/>:<span>ETEF</span>}</div></button>
    <div><strong>{x.title_en}</strong><p>{x.photo_count} photos · {x.is_published?"Published":"Draft"}</p></div>
    <div className="row-actions"><button onClick={()=>openAlbum(x)}>Manage photos</button><button onClick={()=>toggle(x)}>{x.is_published?"Unpublish":"Publish"}</button><button className="danger-text" onClick={()=>deleteAlbum(x)}>Delete</button></div>
   </article>)}</div>
  </section>
  {selected&&<section className="admin-panel gallery-upload-panel">
   <div className="panel-heading"><div><span className="eyebrow">PHOTO LIBRARY</span><h2>{selected.title_en}</h2><p className="panel-subcopy">Files are stored with randomized server filenames. SVG and executable content are rejected.</p></div><button className="admin-button light" onClick={()=>{setSelected(null);setPhotos([])}}>Close</button></div>
   <div className="gallery-dropzone"><input id="gallery-file-input" type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={e=>setFiles(Array.from(e.target.files||[]))}/><label htmlFor="gallery-file-input"><strong>Choose photographs</strong><span>JPEG, PNG or WebP · up to 10 files · 5 MB each</span></label>{files.length>0&&<div className="selected-files">{files.map(f=><span key={`${f.name}-${f.size}`}>{f.name}</span>)}</div>}<button className="admin-button dark" disabled={loading||!files.length} onClick={upload}>{loading?"Uploading…":`Upload ${files.length||""} image${files.length===1?"":"s"}`}</button></div>
   <div className="photo-grid">{photos.map(photo=><article className="photo-card" key={photo.id}><img src={`${API_ORIGIN}${photo.image_url}`} alt={photo.title_en||"ETEF gallery photograph"}/><div className="photo-card-meta"><div><strong>{selected.cover_image_url===photo.image_url?"Cover image":"Gallery image"}</strong><small>{photo.sort_order+1}</small></div><div className="row-actions"><button onClick={()=>cover(photo)} disabled={selected.cover_image_url===photo.image_url}>{selected.cover_image_url===photo.image_url?"Cover":"Set cover"}</button><button className="danger-text" onClick={()=>remove(photo)}>Delete</button></div></div></article>)}{!photos.length&&<div className="admin-empty">No photographs in this album yet.</div>}</div>
  </section>}
 </div>;
}

type Photo={id:string;album_id:string;title_en?:string;title_am?:string;image_url:string;sort_order:number;created_at:string};
function VacancyManager({notify}:{notify:(m:string)=>void}){const[items,setItems]=useState<Vacancy[]>([]),[title,setTitle]=useState(""),[location,setLocation]=useState(""),[date,setDate]=useState("");const load=()=>api<{items:Vacancy[]}>("/admin/vacancies").then(r=>setItems(r.items));useEffect(()=>{load().catch(()=>notify("Unable to load vacancies"))},[]);const add=async()=>{if(!title.trim())return notify("Job title is required");try{await api("/admin/vacancies",{method:"POST",body:JSON.stringify({titleEn:title,location,closingDate:date||null})});setTitle("");setLocation("");setDate("");notify("Vacancy created");load()}catch(e:any){notify(e.message)}};return <div className="admin-content"><section className="admin-panel"><div className="panel-heading"><div><span className="eyebrow">JOB VACANCIES</span><h2>Create and update opportunities</h2></div></div><div className="form-row-admin"><label className="admin-field"><span>Job title</span><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Communications Officer"/></label><label className="admin-field"><span>Location</span><input value={location} onChange={e=>setLocation(e.target.value)} placeholder="Addis Ababa"/></label><label className="admin-field"><span>Deadline</span><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><button className="admin-button dark create-vacancy" onClick={add}>Add vacancy</button></div></section><section className="admin-panel table-panel"><table><thead><tr><th>Position</th><th>Location</th><th>Deadline</th><th>Status</th><th/></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><strong>{x.title_en}</strong></td><td>{x.location||"—"}</td><td>{x.closing_date||"Open"}</td><td><span className={`status-pill ${x.status==="CLOSED"?"closed":""}`}>{x.status}</span></td><td><button className="table-action" onClick={async()=>{const status=x.status==="OPEN"?"CLOSED":"OPEN";try{await api(`/admin/vacancies/${x.id}`,{method:"PATCH",body:JSON.stringify({status})});notify("Vacancy status updated");load()}catch(e:any){notify(e.message)}}}>{x.status==="OPEN"?"Close":"Reopen"}</button></td></tr>)}</tbody></table></section></div>}
function ContentManager({notify}:{notify:(m:string)=>void}){const[form,setForm]=useState<Record<string,string>>({organization_email:"",facebook_url:"",telegram_url:"",linkedin_url:"",youtube_url:""});useEffect(()=>{api<{settings:Record<string,string>}>("/admin/settings").then(r=>setForm(x=>({...x,...r.settings}))).catch(()=>notify("Unable to load settings"))},[]);const save=async()=>{try{await api("/admin/settings",{method:"PUT",body:JSON.stringify(form)});notify("Site settings saved")}catch(e:any){notify(e.message)}};return <div className="admin-content"><section className="admin-panel"><div className="panel-heading"><div><span className="eyebrow">SITE SETTINGS</span><h2>Official contact & social links</h2></div></div><div className="form-row-admin">{Object.entries(form).map(([k,v])=><label className="admin-field" key={k}><span>{k.replaceAll("_"," ")}</span><input value={v} onChange={e=>setForm(f=>({...f,[k]:e.target.value}))} placeholder={k.endsWith("url")?"https://…":""}/></label>)}</div><button className="admin-button dark" onClick={save}>Save settings</button></section><section className="admin-panel"><div className="panel-heading"><div><span className="eyebrow">LANGUAGES</span><h2>Inclusive content architecture</h2></div></div><div className="language-admin"><div><strong>English</strong><span>Primary content language</span></div><div><strong>አማርኛ</strong><span>Priority public language</span></div><div><strong>Future languages</strong><span>Architecture-ready</span></div></div></section></div>}
